// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldGamesMVC.Context;

namespace WorldGamesMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210909225949_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WorldGamesMVC.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<sbyte>("Ativo")
                        .HasColumnType("tinyint");

                    b.Property<string>("DescricaoCompleta")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ImagemThumb")
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Plataforma")
                        .HasColumnType("int");

                    b.Property<float>("Preco")
                        .HasColumnType("FLOAT(10,6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("GameId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WorldGamesMVC.Models.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GeneroNome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("WorldGamesMVC.Models.Game", b =>
                {
                    b.HasOne("WorldGamesMVC.Models.Genero", "Genero")
                        .WithMany("Games")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
